version: '3.6'

volumes:
  postgres:

networks:
  poly:
    name: polyorg

services:
  db:
    image: postgres:14.6
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    command: postgres -c max_connections=200 -c fsync=off -c synchronous_commit=off -c full_page_writes=off
    ports:
      - 65432:5432
    volumes:
      - postgres:/var/lib/postgressql/data
  poly-core:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        BUILD_STAGE: dev
    volumes:
      - .:/usr/src/app
    command:
      - pnpm
      - start:dev
    env_file:
      - ./.env.default
      - ./.env
    ports:
      - 5001:5001
    depends_on:
      - db
    user: ${UID:-1000}:${GID:-1000}
    networks:
      default:
      poly:
        aliases:
          - 'poly-core'
