default: &default
  docker:
    - image: cimg/node:18.3.0
  working_directory: ~/project

install-pnpm: &install-pnpm
  - run:
      name: 'Install pnpm'
      command: 'npm i -g pnpm'

install-packages: &install-packages
  - node/install-packages:
      cache-path: ~/project/node_modules
      override-ci-command: pnpm install

version: 2.1

jobs:
  build:
    <<: *default
    steps:
      - checkout
      - <<: *install-pnpm
      - <<: *install-packages
      - run:
          name: 'Build'
          command: 'pnpm build'

  tests:
    <<: *default
    steps:
      - checkout
      - <<: *install-pnpm
      - <<: *install-packages
      - run:
          name: 'Tests'
          command: 'pnpm test'
      - codecov/upload

  eslint:
    <<: *default
    steps:
      - checkout
      - <<: *install-pnpm
      - <<: *install-packages
      - run:
          name: 'ESlint'
          command: 'pnpm lint'

  prettier:
    <<: *default
    steps:
      - checkout
      - <<: *install-pnpm
      - <<: *install-packages
      - run:
          name: 'Prettier'
          command: 'pnpm format'

orbs:
  node: circleci/node@5.0.3
  codecov: codecov/codecov@3
workflows:
  ci:
    jobs:
      - build
      - tests
      - eslint
      - prettier
